export const numberTrades = {
    "dataset": {
        "id": 38797107,
        "dataset_code": "085692_FO_ALL_NT",
        "database_code": "CFTC",
        "name": "Commitment of Traders - COPPER- #1 (CMX) - Futures and Options - Number of Traders (085692)",
        "description": "Commitment of Traders - COPPER- #1 (CMX) - Futures and Options - Number of Traders<br><br>Contract Market Code: 085692<br><br>Units: CONTRACTS OF 25,000 POUNDS",
        "refreshed_at": "2022-04-07 20:46:10 UTC",
        "newest_available_date": "2022-03-29",
        "oldest_available_date": "2006-06-13",
        "column_names": [
            "Date",
            "Total Traders",
            "Producer/Merchant/Processor/User Longs",
            "Producer/Merchant/Processor/User Shorts",
            "Swap Dealer Longs",
            "Swap Dealer Shorts",
            "Swap Dealer Spreads",
            "Money Manager Longs",
            "Money Manager Shorts",
            "Money Manager Spreads",
            "Other Reportable Longs",
            "Other Reportable Shorts",
            "Other Reportable Spreads",
            "Total Reportable Longs",
            "Total Reportable Shorts"
        ],
        "frequency": "weekly",
        "type": "Time Series",
        "premium": false,
        "limit": null,
        "transform": null,
        "column_index": null,
        "start_date": "2022-03-15",
        "end_date": "2022-03-29",
        "data": [
            [
                "2022-03-29",
                272.0,
                32.0,
                47.0,
                22.0,
                8.0,
                16.0,
                84.0,
                26.0,
                44.0,
                41.0,
                34.0,
                33.0,
                221.0,
                173.0
            ],
            [
                "2022-03-22",
                266.0,
                32.0,
                47.0,
                22.0,
                8.0,
                13.0,
                80.0,
                27.0,
                49.0,
                42.0,
                29.0,
                34.0,
                219.0,
                171.0
            ],
            [
                "2022-03-15",
                255.0,
                32.0,
                45.0,
                23.0,
                6.0,
                15.0,
                76.0,
                32.0,
                52.0,
                42.0,
                25.0,
                32.0,
                212.0,
                171.0
            ]
        ],
        "collapse": null,
        "order": null,
        "database_id": 15257
    }
}